### ISSUE TITLE
No Vanilla Fish

### ISSUE THREAD

**Issue by gr8pefish** [ChatFawkes/Flux-Galaxy#1]
There is no way to get vanilla fish, might want to add in a minetweaker recipe to convert harvestcraft fish to vanilla ones.

**Comment by ChatFawkes** [comment]
By not obtainable you mean that they can't be fished (via a fishing rod)?

**Comment by gr8pefish** [comment]
Nevermind, they are obtainable, just harder to get. No big deal.
