### ISSUE TITLE
Genetics is unusable

### ISSUE THREAD

**Issue by BaIthamel** [ChatFawkes/Flux-Galaxy#3]
The genetics mod is broken in v6b as available in the latest FTB pack, apparently it is fixed in v7.

**Comment by ChatFawkes** [comment]
The latest version of the pack (0.8pre3) has Binnie's Mods 2.0pre7 and many other new versions of mods. That is available [here](http://www.technicpack.net/modpack/fluxgalaxy.560255) as a latest version.
