### ISSUE TITLE
RedLogic recipes

### ISSUE THREAD

**Issue by ghost** [ChatFawkes/Flux-Galaxy#5]
RedLogic's recipes which need a dye in it are bit messed up (e.g: white lamps need ink sac / black dye instead of bone meal / white dye). It is fixed by updating ImmibisCore to 59.0.8
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1444476-1-7-2-redlogic-replacement-for-rp2-wiring-logic?comment=666

**Comment by ChatFawkes** [comment]
Thanks for the note, I'll be updating it (as well as loads of other mods) in 0.8.3, which I'm hoping to have out by tonight.

**Comment by ChatFawkes** [comment]
Immibis Core was updated to 59.0.8 in 0.8.3, so this should be fixed.
