### ISSUE TITLE
World Gen Crash

### ISSUE THREAD

**Issue by mtlballer** [ChatFawkes/Flux-Galaxy#67]
Got this crash while exploring the Overworld. Pretty sure it's something world gen related, but I could be wrong. So far I've tried moving my player away from the area using MCedit(made a backup first) with no success. Have not yet tried pruning said area. Running Java 8u25 if that matters. Running version 0.7.8 on the FTB launcher

http://pastebin.com/9ryzLRjU

**Comment by mtlballer** [comment]
Pruning of the new area and a player move resolved the issue for now, Returning to the area in a backup has created a new crash type. Crash report follows.

http://pastebin.com/n2HQf3bU

**Comment by ChatFawkes** [comment]
Interesting that report seems to point towards BluePower as the culprit, gonna look into it.

**Comment by ChatFawkes** [comment]
Alright I have updated BluePower in 0.7.10. Could you possibly try loading up those worlds to see if you still crash?

**Comment by mtlballer** [comment]
Yep I'll give it a go once the update hits the launcher.

**Comment by ChatFawkes** [comment]
I can confirm that the latest pack version doesn't fix this error. Here is a [similar crash report](http://pastebin.com/uG6V1gKQ) that was produced by someone on 0.7.10. Best help I could find for this issue was this [forum post](http://forums.technicpack.net/topic/57049-most-common-issues-and-fixes-and-known-problems/#entry467892).

**Comment by mtlballer** [comment]
This world was in SSP, I've since opened it to Multiplayer for friends, but the fix is useless for me, We've agreed to avoid the area, and I can just do the same for any future area like this, I have no problem marking this as solved if you wish, as there's literally nothing you can do at this time about it. I will still test it it once the next version comes out, and report back.

**Comment by ChatFawkes** [comment]
progwml6/Natura#212 might be related to this. The crash reports when attempting to load the world again are similar.

**Comment by votex09** [comment]
I also get a similar crash... I notice it pops up after using a script from Applied Energistics 2 - Possible Meteorite Issue?
http://pastebin.com/Bc65jAsW

**Comment by mtlballer** [comment]
lastest crash report when visiting the problem area in 0.7.13 . All testing is done in SSP.

http://pastebin.com/7Uq98tGP

**Comment by mtlballer** [comment]
It would seem this is fixed in 0.7.14 . The trouble area is no longer crashing.

**Comment by ChatFawkes** [comment]
Hmm that's good to hear, but I'm still not sure if this issue is fixed. I think this might be related to MinecraftForge/MinecraftForge#1686.

**Comment by ChatFawkes** [comment]
Good news I believe this is fixed in forge now.
