### ISSUE TITLE
Initializing not finishing

### ISSUE THREAD

**Issue by ryfitz64** [ChatFawkes/Flux-Galaxy#70]
i start  up the pack and it goses through the motions till it hits the Initializing and right at the end it freezes pls help

**Comment by ChatFawkes** [comment]
Can I get a pastebin of your latest log?

**Comment by ryfitz64** [comment]
Yeah here you go pastebin.com/VAVU8FwF

**Comment by ChatFawkes** [comment]
In your Launcher Options add this to the Java Parameters:

`-XX:PermSize=192M`

**Comment by ryfitz64** [comment]
i have started the game and it now on a black screen

**Comment by ryfitz64** [comment]
![image](https://cloud.githubusercontent.com/assets/10547365/5762663/c66ffb80-9cb1-11e4-8528-5f25dbb9f2e6.png)

**Comment by ChatFawkes** [comment]
Does it crash after it's done Initializing?

**Comment by ryfitz64** [comment]
no it just goes to this

**Comment by ChatFawkes** [comment]
Well if you add that parameter I gave you in your Java Parameters/Options then it should fix the crash because it was caused bt not having enough PermGen.

**Comment by ryfitz64** [comment]
yeah i did it just took a hell of a lot longer then norm ty

**Comment by ryfitz64** [comment]
![image](https://cloud.githubusercontent.com/assets/10547365/5762755/7f8b3e04-9cb2-11e4-980e-b617c77ac33c.png)
