### ISSUE TITLE
Crash when loading world, I don't know what i did...

### ISSUE THREAD

**Issue by Elvenoob** [ChatFawkes/Flux-Galaxy#71]
Edit: Shortened post
https://gist.github.com/ChatFawkes/0462c362ae2eec528aa3

**Comment by ChatFawkes** [comment]
Seems like some sort bug with Thaumcraft and WAILA. Try disabling WAILA and see if you can load the world

**Comment by Elvenoob** [comment]
Okay, That worked, I think I saved and quit looking at Thauncraft's Arcane Worktable, I'm going to try re-adding Walia now that I'm looking at my chests instead.

**Comment by Elvenoob** [comment]
Okay, Fully fixed now, It seems it'll just crash if you save and quit looking at the Arcane worktable, and maybe the 2 block desk as well.

**Comment by ChatFawkes** [comment]
Thanks for letting me know, I will report it to the WAILA devs.

**Comment by evenas98** [comment]
I think i have the same problem, just reported on issue tracker for WAILA

**Comment by ChatFawkes** [comment]
Fixed in 0.7.15+.
