### ISSUE TITLE
Me conduit crash on startup

### ISSUE THREAD

**Issue by loco7185** [ChatFawkes/Flux-Galaxy#72]
i placed down a me conduit next to a ae2 cable and now when it starts it crashes as soon as world is ready if any one has any temp fix that would be great.

i have tried disabling the me conduits but that didnt work

https://gist.github.com/d66221c84665a39576d7.git

**Comment by ChatFawkes** [comment]
Can I get a copy of the crash report?

**Comment by mtlballer** [comment]
Pretty sure this is related to the ME conduit only, just got a similar crash when attempting to use the ME conduit.  http://pastebin.com/d2Q0rviS

Unfortunately it seems the only fix for this is to completely remove the ME conduit and to never use it again. According to https://github.com/CrazyPants/EnderIO/issues/1626 , the version of AE2 in use is not supported.

**Comment by ChatFawkes** [comment]
Yah this is probably fixed in 0.7.12 if the issue seems to be with AE2 rv1.

**Comment by magicbadger** [comment]
Got the same bug and stack trace here - not sure when 0.7.12 will be live on FTB but would manually upgrading AE2 help things?

**Comment by ChatFawkes** [comment]
Well there are some mods that might break on updating to AE rv2 (Extracells and Thaumic Energistics), so I'd suggest waiting for 0.7.13 which will be a recommended version on all launchers. I only publish latest version on the Technic Launcher.

**Comment by mtlballer** [comment]
This appears to be fixed in 0.7.13.
