### ISSUE TITLE
Tinker Tools no longer repairing

### ISSUE THREAD

**Issue by mtlballer** [ChatFawkes/Flux-Galaxy#74]
Not sure if this is intended or not, but my tinker tools are no longer self repairing.

**Comment by ChatFawkes** [comment]
Yeah this is a known issue. I will report it to the TCon devs unless it's already been reported. On the plus side at least auto repair still works on ammo.

**Comment by ChatFawkes** [comment]
Should be fixed in 0.7.15+.
