### ISSUE TITLE
Mekanism pipes connecting to Salination Valve

### ISSUE THREAD

**Issue by magicbadger** [ChatFawkes/Flux-Galaxy#75]
At some upgrade point (now on 0.7.14a), Mekanism mechanical pipes have stopped connecting to Salination Valves, although they connect to Railcraft tanks just fine.

Haven't tried any alternative piping yet.

**Comment by ChatFawkes** [comment]
Thanks for the report will look into it.

**Comment by ChatFawkes** [comment]
They seem to be pushing and pulling properly in 0.7.16+. Here is a [video](https://www.fluxgalaxy.com/upload/2015-02-16_13-13-29.mp4) of that in action.

So I'm closing this issue because I can't replicate it in the latest pack version.
